openshift/csi-operator

cmd/csi-operator/main.go
1 hour should be fine in production.
=> Increase resync period

README.md, docs/configuration.md, docs/usage.md, pkg/generated/manifests/default-config.yaml
- Add note about OpenShift
- Add usage.md
- Fix operator startup
=> Documentation update

pkg/controller/csidriverdeployment/csidriverdeployment_controller.go, pkg/controller/csidriverdeployment/objects.go, pkg/controller/csidriverdeployment/objects_test.go
Don't rely on owner reference and fix listing of storage classes.
=> Fix deletion of non-namespaced objects

Makefile, cmd/csi-operator/main.go, version/version.go
=> Embed git version into the operator binary

cmd/csi-operator/main.go, test/e2e/e2e_test.go
The leader election works only when the operator is running in-cluster.
Fixes: #15
=> Add leader election to the operator

deploy/ebs.yaml
=> Add EBS sample deployment file

pkg/controller/csidriverdeployment/objects.go, pkg/controller/csidriverdeployment/objects_test.go, pkg/controller/csidriverdeployment/testdata/01-simple-deployment/out-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/02-custom-service-account/out-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/03-no-liveness-probe/out-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/04-noop/in-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/05-overwrite-changes/in-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/05-overwrite-changes/out-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/06-user-changes/in-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/06-user-changes/out-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/07-storageclass-changes/in-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/08-deletion/in-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/09-deletion-noop/in-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/11-sync-status-deployment/in-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/12-sync-status-daemonset/in-daemonset.yaml, pkg/controller/csidriverdeployment/testdata/13-security-context/out-daemonset.yaml
Fixes https://github.com/openshift/csi-operator/issues/42
=> Add kubelet-registration-path flag to csi-driver-registrar

.ci-operator.yaml
With the right go version for 4.15 (so far).
=> Add ci-operator config

pkg/generated-assets/generated_assets.go, pkg/generated-assets/sanitize.go, pkg/generated-assets/sanitize_test.go, pkg/generator/asset_generator.go
=>  OCPBUGS-25125: Add test AssetOrderer

legacy/azure-disk-csi-driver-operator/.gitignore
This should fix brewpub field.
=> STOR-1713: Don't ignore azure-disk-csi-driver-operator

assets/common/sidecars/node_driver_registrar.yaml, assets/overlays/aws-ebs/generated/hypershift/node.yaml, assets/overlays/aws-ebs/generated/standalone/node.yaml, assets/overlays/azure-disk/generated/hypershift/node.yaml, assets/overlays/azure-disk/generated/standalone/node.yaml, pkg/driver/aws-ebs/aws_ebs.go, pkg/driver/azure-disk/azure_disk.go, pkg/generator/asset_generator.go, pkg/generator/types.go
Fixes https://issues.redhat.com/browse/OCPBUGS-26924
=> OCPBUGS-26924: Add healthcheck for node-driver-registrar container

Dockerfile.samba
Add Dockerfile for Samba operator
=> STOR-1726: Add Dockerfile for Samba operator

assets/overlays/samba/generated/standalone/configmap_and_secret_reader_provisioner_binding.yaml, assets/overlays/samba/generated/standalone/controller_privileged_binding.yaml, assets/overlays/samba/generated/standalone/lease_leader_election_binding.yaml, assets/overlays/samba/generated/standalone/main_provisioner_binding.yaml, assets/overlays/samba/generated/standalone/node_privileged_binding.yaml, assets/overlays/samba/patches/binding_with_namespace_placeholder_controller.yaml, assets/overlays/samba/patches/binding_with_namespace_placeholder_node.yaml, pkg/driver/samba/samba.go
See discussion here: https://github.com/openshift/csi-operator/pull/237#pullrequestreview-2180840306
=> NO-JIRA: use service account namespace placeholder for smb role bindings

assets/overlays/aws-efs/generated/standalone/controller.yaml, assets/overlays/aws-efs/patches/controller_add_driver.yaml, config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml, config/aws-efs/manifests/stable/image-references, doc/aws-efs/README.md
=> STOR-1993: add init container in EFS CSI controller pod

config/aws-efs/manifests/stable/image-references
https://github.com/openshift/csi-operator/pull/252/files#r1719471717
CC @openshift/storage
=> OCPBUGS-38578: efs: fix tools image reference

config/aws-efs/manifests/aws-efs-csi-driver-operator.package.yaml, config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml, config/samba/manifests/preview/smb-csi-driver-operator.clusterserviceversion.yaml, config/samba/manifests/smb-csi-driver-operator.package.yaml
https://issues.redhat.com/browse/STOR-2009
/label px-approved
/label docs-approved
=> STOR-2009: Bump OLM metadata to 4.18

assets/overlays/aws-ebs/generated/hypershift/controller.yaml, assets/overlays/aws-ebs/generated/standalone/controller.yaml, assets/overlays/aws-ebs/patches/controller_add_driver.yaml, assets/overlays/aws-efs/generated/standalone/controller.yaml, assets/overlays/aws-efs/generated/standalone/node.yaml, assets/overlays/aws-efs/patches/controller_add_driver.yaml, assets/overlays/aws-efs/patches/node_add_driver.yaml, assets/overlays/samba/generated/standalone/controller.yaml, assets/overlays/samba/generated/standalone/node.yaml, assets/overlays/samba/patches/controller_add_driver.yaml, assets/overlays/samba/patches/node_add_driver.yaml, config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml, config/samba/manifests/preview/smb-csi-driver-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/OCPBUGS-38620
=> OCPBUGS-38620: Some CSI driver containers missing terminationMessagePolicy

assets/overlays/aws-efs/generated/standalone/controller.yaml, assets/overlays/aws-efs/patches/controller_add_driver.yaml, config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml, config/aws-efs/manifests/stable/image-references, doc/aws-efs/README.md
=> OCPBUGS-38815: add init container in EFS CSI controller pod

assets/overlays/aws-ebs/generated/hypershift/controller.yaml, assets/overlays/aws-ebs/generated/standalone/controller.yaml, assets/overlays/aws-ebs/patches/controller_add_driver.yaml, assets/overlays/aws-efs/generated/standalone/node.yaml, assets/overlays/aws-efs/patches/node_add_driver.yaml, assets/overlays/samba/generated/standalone/controller.yaml, assets/overlays/samba/generated/standalone/node.yaml, assets/overlays/samba/patches/controller_add_driver.yaml, assets/overlays/samba/patches/node_add_driver.yaml, config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml, config/samba/manifests/preview/smb-csi-driver-operator.clusterserviceversion.yaml
Manual backport of https://github.com/openshift/csi-operator/pull/262
=> [4.17] OCPBUGS-38736: Some CSI driver containers missing terminationMessagePolicy

pkg/openstack-cinder/config/configsync.go
We (unfortunately) need to extract our CA cert from the cloud-provider configuration. In a Hypershift context, this lives in the control plane cluster and has a different name. Correct both the cluster and name used and remove a check for missing config maps: this should *always* exist in a healthy cluster, given `cloud-provider-openstack` has a hard dependency on it.
=> OSASINFRA-3535: openstack-cinder: Watch management cluster for cloud-provider config

pkg/driver/common/operator/hooks.go
missed as part of https://issues.redhat.com/browse/CNV-38758
=> OCPBUGS-43357: support hcp tolerations

README.md
=> NO-JIRA: Fixed typo in README.md

config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml, config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/STOR-1880
=> STOR-1880: Role and ClusterRole with too wide permissions

config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml, config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/STOR-1877
=> STOR-1877: Run operators without root user control

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/crypto/crypto.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go, vendor/github.com/openshift/library-go/pkg/operator/genericoperatorclient/dynamic_operator_client.go, vendor/modules.txt
https://issues.redhat.com/browse/OCPBUGS-54230
=> OCPBUGS-54230: Bump library-go

config/aws-efs/manifests/aws-efs-csi-driver-operator.package.yaml, config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml, config/samba/manifests/smb-csi-driver-operator.package.yaml, config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
https://issues.redhat.com/browse/STOR-2408
=> STOR-2408: Bump OLM metadata to 4.20

pkg/efscreate/create.go
When no `STORAGECLASS_LOCATION` or `MANIFEST_LOCATION` env. var is set, print their content to the log.
This is useful for manual invocation, when user forgets to set the variables. `create-efs-volume` is not reentrant (tries to create already existing SecurityGroup) and the manifests would be lost.
Sample output:
```
...
I0604 15:50:50.428148  546693 efs.go:99] Waiting for MountTargets to get available
I0604 15:52:14.389490  546693 efs.go:176] successfully created file system fs-09dd7e0fdce5f920c
I0604 15:52:14.389535  546693 create.go:67] created fsID: fs-09dd7e0fdce5f920c
I0604 15:52:14.389573  546693 create.go:162] No STORAGECLASS_LOCATION specified, printing to log:
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: efs-sc
provisioner: efs.csi.aws.com
mountOptions:
- …
```
=> NO-JIRA: create-efs-volume: print files to log as a fallback

assets/overlays/aws-ebs/generated/hypershift/controller.yaml, assets/overlays/aws-ebs/generated/standalone/controller.yaml, assets/overlays/aws-ebs/patches/controller_add_driver.yaml
https://issues.redhat.com//browse/STOR-2330
This PR subscribes AWS-EBS CSI driver controller pods to NPs from https://github.com/openshift/cluster-storage-operator/pull/579.
=> STOR-2330: Add labels to subscribe AWS-EBS CSI driver controller to NPs

assets/overlays/samba/generated/standalone/controller.yaml, assets/overlays/samba/patches/controller_add_driver.yaml, config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
https://issues.redhat.com//browse/STOR-2331
This PR subscribes SMB CSI driver operator and controller pods to NPs from https://github.com/openshift/cluster-storage-operator/pull/579
=> STOR-2331: Add labels to subscribe SMB CSI driver operator and controller to NPs

pkg/driver/aws-ebs/aws_ebs.go, pkg/operator/config/config.go, pkg/operator/starter.go, vendor/github.com/openshift/library-go/pkg/operator/staleconditions/remove_stale_conditions.go, vendor/modules.txt
This is a manual cherry-pick of https://github.com/openshift/csi-operator/pull/413
=> OCPBUGS-60470: Backport stale conditions fix 

go.mod, go.sum, vendor/github.com/openshift/library-go/pkg/operator/certrotation/cabundle.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/client_cert_rotation_controller.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/signer.go, vendor/github.com/openshift/library-go/pkg/operator/certrotation/target.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go, vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go, vendor/modules.txt
Fixes https://issues.redhat.com/browse/OCPBUGS-60596
=> [4.18] OCPBUGS-60596: Bump library-go to fix assignment to nil map issue
