openshift/csi-operator

cmd/csi-operator/main.go
pkg/controller/handler.go
pkg/controller/objects.go

The operator is interested only in things it manages, not in all ServiceAccounts, DaemonSets, Deployments and so on. To find the managed things we can use a label selector.

Use label selector for informers.

---

deploy/openshift/image-references
deploy/operator.yaml
deploy/prerequisites/04_namespace.yaml
deploy/prerequisites/05_sa.yaml
deploy/prerequisites/06_role_binding.yaml
deploy/prerequisites/07_config.yaml

"csi-operator" is too generic and matches e.g. namespace names. Use "registry.svc.ci.openshift.org/openshift/origin-v4.0:csi-operator".
And use "openshift-csi-operator" namespace when at it.

Fix operator images

---

deploy/samples/gce.yaml
deploy/samples/hostpath.yaml
pkg/controller/objects.go
pkg/controller/objects_test.go

Various Kubernetes distributions can have different location of /var/lib/kubelet. We want the CSIDriverDeployment to be the same for them.

Add /var/lib/kubelet HostPath directory to node drivers

---

pkg/controller/csidriverdeployment/csidriverdeployment_controller.go

Even if CSIDriverDeployment was not found and keep requeuing, nobody
can notice the issue currently.
This patch outputs the error message via glog and event log, so users
can notice the error message.

Output error message when failed to get CSIDriverDeployment and requeued

---

pkg/controller/csidriverdeployment/objects_test.go

Currently golint (`./hack/verify-golint.sh `) fails due to following error:
```
$ ./hack/verify-golint.sh 
!!! golint detected the following problems:
./pkg/controller/csidriverdeployment/objects_test.go:19:25: should omit type corev1.Container from declaration of var defaultDriverContainer; it will be inferred from the right-hand side
./pkg/controller/csidriverdeployment/objects_test.go:26:12: should omit type v1alpha1.CSIDriverDeployment from declaration of var defaultCR; it will be inferred from the right-hand side
```
This patch fixes the error.

Fix golint error

---

deploy/samples/hostpath.yaml

In Kubernetes 1.13, dynamic driver registration is preferred and CSI driver must report non-empty node name. This is fixed in newer hostpath drivers.

Fix hostpath image sample to support dynamic registration

---

Makefile

Add `verify-generated-assets` make target that just re-generates the assets + calls `git diff`. It will produce false negatives when users have unstaged changes in their workdir, but it's good enough for CI. It's similar to what [openshift/api uses](https://github.com/openshift/api/blob/b8a18fdc040de6208d49111ac776ac08b98e6bb7/Makefile#L67).

Verify generated assets in `make verify`

---

cmd/generator/main.go
hack/update-generated-assets.sh

Generator now re-generates all assets of all CSI drivers in a single call. So we don't need to list the drivers in `hack/update-generated-assets.sh`.
It should be more obvious to maintain one `main.go` instead of `hack/` script.

Update all generated assets in a single run

---

pkg/clients/builder.go
pkg/clients/clients.go
pkg/clients/fake.go
pkg/driver/aws-ebs/aws_ebs.go
pkg/driver/aws-ebs/aws_ebs_test.go
pkg/driver/common/operator/hooks.go
pkg/driver/common/operator/hooks_test.go
pkg/operator/starter.go

Most of the clients are for the guest cluster, keep ControlPlane for the mgmt cluster.

Drop Guest prefix from client names

---

vendor/golang.org/x/net/http2/Dockerfile
vendor/golang.org/x/net/http2/Makefile

Fix verify-deps by adding missing files added by `go mod tidy` && `go mod vendor`. Not sure how the current vendor got merged without them.

Fix vendoring of golang.org/x/net

---

pkg/operator/starter.go

To make the new aws-ebs-csi-driver-operator easily distinguishable from the old one.

STOR-1500: Add log for the new operator

---

assets/overlays/aws-ebs/generated/hypershift/controller.yaml
assets/overlays/aws-ebs/generated/standalone/controller.yaml
assets/overlays/aws-ebs/patches/controller_add_driver.yaml
legacy/aws-ebs-csi-driver-operator/assets/controller.yaml

Add `--batching=true`.
cc @openshift/storage 
CI will likely fail until [the driver rebase](https://github.com/openshift/aws-ebs-csi-driver/pull/244) is merged.

STOR-1400: Add support for Batch DescribeVolume

---

README.md

Copy/paste from https://github.com/openshift/aws-ebs-csi-driver-operator with two fixes:
* `10_cr.yaml` is now called `operator.openshift.io_v1_clustercsidriver_ebs.csi.aws.com.yaml`
* the binary (`aws-ebs-csi-driver-operator`) is in `bin/` dir now

NO-JIRA: Add "Quick start" section to `README.md`

---

pkg/generated-assets/generated_assets.go
pkg/generated-assets/sanitize.go
pkg/generator/asset_generator.go

Make sure SAs and Roles are created before bindings, followed by other resources like DS and Deployments.

OCPBUGS-25125: Create RBAC objects first

---

assets/overlays/aws-ebs/base/csidriver.yaml
assets/overlays/aws-ebs/generated/hypershift/csidriver.yaml
assets/overlays/aws-ebs/generated/standalone/csidriver.yaml

Restore `seLinuxMount: true` in AWS EBS CSIDriver instance that we lost when moving to csi-operator repo.

OCPBUGS-24245: Add selinux

---

.github/dependabot.yaml

Add dependabot configuration that opens PRs for *all* dependencies (not only the direct ones and not only CVEs). Group the largest groups together:
- golang.org/x/*
- k8s.io/* and related repos
- opentelemetry.io/*
The rest should be ungrouped (I hope, documentation is not clear).
The PRs get automatic `ok-to-test` and `*-approved` labels.

NO-JIRA: Add dependabot configuration

---

pkg/operator/starter.go

When `RunOperator()` returns no error, library-go waits for leader election goroutine to release the leadership before exiting.
An error returned from `RunOperator()` takes a shortcut and leads to much faster `exit(1)`, not giving the election goroutine time to release its lease. A subsequent operator pod needs to wait for the old lease to expire, which slows down cluster upgrade and any development / debugging that needs the operator restarted.

STOR-1714: AWS EBS operator: Release leadership on SIGTERM

---

legacy/aws-ebs-csi-driver-operator/test/e2e/manifest.yaml
legacy/azure-disk-csi-driver-operator/test/e2e/manifest.yaml
legacy/azure-file-csi-driver-operator/test/e2e/manifest.yaml

For all CSI drivers in this repository, i.e. aws-ebs, azure-disk and azure-file. The test manifests are still in the legacy/ folder.

STOR-1464: Enable RWOP tests in CI

---

Makefile
test/e2e/aws-ebs/manifest.yaml
test/e2e/azure-disk/manifest.yaml
test/e2e/azure-file/manifest.yaml

This PR copies the test manifests from the `legacy` dir to a top-level `test` dir so we can eventually remove the legacy dir (after updating CI jobs).
```
$ cp legacy/aws-ebs-csi-driver-operator/test/e2e/manifest.yaml test/e2e/aws-ebs/
$ cp legacy/azure-disk-csi-driver-operator/test/e2e/manifest.yaml test/e2e/azure-disk/
$ cp legacy/azure-file-csi-driver-operator/test/e2e/manifest.yaml test/e2e/azure-file/
```
Also remove the legacy test-unit and verify targets from the Makefile (we should be running these against the code we compile instead).

OCPBUGS-30620: move test manifests to top-level directory

---

.github/dependabot.yaml

Allow dependabot to open only security update PRs.
Dependabot [docs](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file) say:
> If you only require security updates and want to exclude version updates,
> you can set open-pull-requests-limit to 0 in order to prevent version
> updates for a given package-ecosystem
I am curious what it does and how noisy is it going to be. Hoping for just few PRs per month, if any.

NO-JIRA: Configure dependabot for security updates only

---

assets/overlays/aws-ebs/generated/hypershift/node.yaml
assets/overlays/aws-ebs/generated/standalone/node.yaml
assets/overlays/aws-ebs/patches/node_add_driver.yaml

Using a newly introduced option --reserved-volume-attachments, explicitly reserve 1 AWS EBS volume attachment for the root disk and leave the other attachment to PVs/PVCs.
This disables bad heuristics in the CSI driver, see the linked bug.
/hold
for https://github.com/openshift/aws-ebs-csi-driver/pull/260 to be merged first

OCPBUGS-23260: Explicitly reserve 1 attachment for the root disk

---

assets/overlays/azure-file/generated/hypershift/controller.yaml
assets/overlays/azure-file/generated/standalone/controller.yaml
assets/overlays/azure-file/patches/controller_add_driver.yaml

`azcopy` tool needs a writeable location for logs:
Before fix:
```
sh-5.1$ azcopy 
2024/03/04 12:41:21 Problem making .azcopy directory. Try setting AZCOPY_LOG_LOCATION env variable. mkdir /.azcopy: permission denied
sh-5.1$ export AZCOPY_LOG_LOCATION=/tmp
sh-5.1$ azcopy
2024/03/04 12:41:34 Problem making .azcopy directory. Try setting AZCOPY_JOB_PLAN_LOCATION env variable. mkdir /.azcopy: permission denied
sh-5.1$ export AZCOPY_JOB_PLAN_LOCATION=/tmp
sh-5.1$ azcopy
AzCopy 10.22.1
```
After fix:
```
$ oc describe pvc/pvc-1-clone
Name:          pvc-1-clone
Namespace:     default
StorageClass:  azurefile-csi
Status:        Bound
Volume:        pvc-89a7a986-45e9-4357-a497-1a4fbd2dd229
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes …
```

STOR-1794: add location for azcopy logs

---

Dockerfile.test
Makefile
test/e2e/aws-ebs/manifest.yaml

This is sort of a backport of https://github.com/openshift/csi-operator/pull/194 to 4.15 where aws-ebs is built (before azure-disk and azure-file were added). The intent is to eventually remove the `legacy` directory, which means we have to move the manifests first.
It also creates Dockerfile.test which already exists in the master branch but not 4.15.
```
$ cp legacy/aws-ebs-csi-driver-operator/test/e2e/manifest.yaml test/e2e/aws-ebs/
$ cp Dockerfile.aws-ebs.test Dockerfile.test
```
Also remove the legacy test-unit and verify targets from the Makefile (we should be running these against the code we compile instead).

[4.15] OCPBUGS-30621: move test manifest to top-level directory

---

assets/overlays/samba/generated/standalone/configmap_and_secret_reader_provisioner_binding.yaml
assets/overlays/samba/generated/standalone/controller.yaml
assets/overlays/samba/generated/standalone/controller_pdb.yaml
assets/overlays/samba/generated/standalone/controller_privileged_binding.yaml
assets/overlays/samba/generated/standalone/controller_sa.yaml
assets/overlays/samba/generated/standalone/csidriver.yaml
assets/overlays/samba/generated/standalone/lease_leader_election_binding.yaml
assets/overlays/samba/generated/standalone/lease_leader_election_role.yaml
assets/overlays/samba/generated/standalone/main_provisioner_binding.yaml
assets/overlays/samba/generated/standalone/manifests.yaml
assets/overlays/samba/generated/standalone/node.yaml
assets/overlays/samba/generated/standalone/node_privileged_binding.yaml
assets/overlays/samba/generated/standalone/node_sa.yaml
assets/overlays/samba/generated/standalone/privileged_role.yaml
cmd/smb-csi-driver-operator/main.go
pkg/driver/samba/samba.go

This PR implements the minimal set of go-files and yaml-assets to enable the command
```
./bin/csi-driver-smb-operator start --kubeconfig $KUBECONFIG --namespace openshift-cluster-csi-drivers
```
to install and run CIFS/Samba CSI driver:
```
$ oc get po -n openshift-cluster-csi-drivers
csi-smb-node-5hvqm                           3/3     Running   0          14s
csi-smb-node-f7mn2                           3/3     Running   0          14s
smb-csi-driver-controller-8657649897-dw47d   3/3     Running   0          16s
smb-csi-driver-controller-8657649897-fht45   3/3     Running   0          16s
```

STOR-1726: Minimal implementation of CIFS/Samba CSI driver operator

---

assets/overlays/samba/generated/standalone/node.yaml
assets/overlays/samba/generated/standalone/node_privileged_binding.yaml
assets/overlays/samba/generated/standalone/node_sa.yaml

`s/csi-smb-node-sa/smb-csi-driver-node` everywhere to be consistent with other driver's namings.

STOR-1726: Simple rename of objects in `assets/overlays/samba/generated/standalone/`

---

test/e2e/samba/manifest.yaml
test/e2e/samba/samba-server.yaml

Together with a yaml file to run a simple samba server.
I expect I will need some changes in the samba-server yaml, but I need to start with something to be able to experiment with CI.

 STOR-1726: Add test manifest for SMB CSI driver

---

config/samba/bundle.Dockerfile
config/samba/manifests/art.yaml
config/samba/manifests/preview/image-references
config/samba/manifests/preview/smb-csi-driver-operator.clusterserviceversion.yaml
config/samba/manifests/smb-csi-driver-operator.package.yaml
config/samba/metadata/annotations.yaml
hack/.gitignore
hack/create-samba-bundle

All metadata + scripts for the SMB CSI driver operator. This is copy + paste of AWS EFS metadata, I only had to add permissions to create/modify PodDisruptionBudgets that we don't use in EFS.
Tested using:
1. build the operator image + push it somewhere (`quay.io/jsafrane/scratch:smbo1`)
2. (using the upstream driver image, `registry.k8s.io/sig-storage/smbplugin:v1.14.0`):
```
./create-samba-bundle registry.k8s.io/sig-storage/smbplugin:v1.14.0 quay.io/jsafrane/scratch:smbo1 quay.io/jsafrane/scratch:bundle3  quay.io/jsafrane/scratch:index3
```
It will build the bundle + index image, push them to quay and generate CatalogSource on stdout.
3. Apply the generated CatalogSource:
```
oc apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: smb
namespace: …
```

STOR-1726: Add OLM metadata for SMB operator

---

pkg/driver/azure-disk/azure_disk.go

xref: https://github.com/openshift/azure-disk-csi-driver-operator/blob/f2d8d99d96e98c35fea10e28a9fc897112894b42/pkg/operator/starter.go#L202
CC @openshift/storage

OCPBUGS-31306: Azure Disk: Add cluster-wide proxy in the driver container in the node

---

pkg/driver/azure-file/azure_file.go

- Root cause
The `config.openshift.io/inject-proxy: csi-driver` annotation exist in the daemonset but the proxy does not inject to the csi-driver container)
- Ref
https://github.com/openshift/azure-file-csi-driver-operator/blob/main/pkg/operator/starter.go#L171

OCPBUGS-31044: Add cluster-wide proxy in the azure-file driver node container

---

pkg/driver/aws-ebs/aws_ebs.go
pkg/driver/azure-disk/azure_disk.go
pkg/driver/azure-file/azure_file.go
pkg/driver/samba/samba.go
pkg/operator/config/config.go
pkg/operator/starter.go
pkg/operator/starter_test.go

This PR allows the smb-csi-driver-operator to clean up its static resources when the ClusterCSIDriver is removed.
The approach is the same as https://github.com/openshift/secrets-store-csi-driver-operator/pull/8 (see also: [secrets-store enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/storage/csi-secrets-store.md#uninstalling-csi-driver)). This should allow us to follow a standard approach when moving other OLM operators to csi-operator just by setting `Removable: true` in the `OperatorConfig`.
Operators which are _not_ removable will not define conditional functions, and will behave the same as before with the static resources controller.
Simple manual test:
1) Create ClusterCSIDriver and wait for operator to create static resources:
```
$ oc apply -f - …
```

STOR-1726: Delete static resources when ClusterCSIDriver is removed

---

assets/common/sidecars/livenessprobe.yaml
assets/overlays/aws-ebs/generated/hypershift/controller.yaml
assets/overlays/aws-ebs/generated/hypershift/node.yaml
assets/overlays/aws-ebs/generated/standalone/controller.yaml
assets/overlays/aws-ebs/generated/standalone/node.yaml
assets/overlays/azure-disk/generated/hypershift/controller.yaml
assets/overlays/azure-disk/generated/hypershift/node.yaml
assets/overlays/azure-disk/generated/standalone/controller.yaml
assets/overlays/azure-disk/generated/standalone/node.yaml
assets/overlays/azure-file/generated/hypershift/controller.yaml
assets/overlays/azure-file/generated/hypershift/node.yaml
assets/overlays/azure-file/generated/standalone/controller.yaml
assets/overlays/azure-file/generated/standalone/node.yaml

For easier debugging. And it's required in OCP operators.

OCPBUGS-28230: Add terminationMessagePolicy to all containers

---

assets/overlays/aws-ebs/generated/hypershift/controller.yaml
assets/overlays/aws-ebs/generated/standalone/controller.yaml
assets/overlays/azure-disk/generated/hypershift/controller.yaml
assets/overlays/azure-disk/generated/standalone/controller.yaml
assets/overlays/azure-file/generated/hypershift/controller.yaml
assets/overlays/azure-file/generated/standalone/controller.yaml
assets/overlays/samba/base/configmap_and_secret_reader_provisioner_binding.yaml
assets/overlays/samba/base/controller_privileged_binding.yaml
assets/overlays/samba/base/csidriver.yaml
assets/overlays/samba/generated/standalone/controller.yaml
assets/overlays/samba/generated/standalone/controller_pdb.yaml
assets/overlays/samba/generated/standalone/controller_sa.yaml
assets/overlays/samba/generated/standalone/kube_rbac_proxy_binding.yaml
assets/overlays/samba/generated/standalone/kube_rbac_proxy_role.yaml
assets/overlays/samba/generated/standalone/manifests.yaml
assets/overlays/samba/generated/standalone/node.yaml
assets/overlays/samba/generated/standalone/node_privileged_binding.yaml
assets/overlays/samba/generated/standalone/node_sa.yaml
assets/overlays/samba/generated/standalone/privileged_role.yaml
assets/overlays/samba/generated/standalone/prometheus_binding.yaml
assets/overlays/samba/generated/standalone/prometheus_role.yaml
assets/overlays/samba/generated/standalone/service.yaml
assets/overlays/samba/generated/standalone/servicemonitor.yaml
assets/overlays/samba/patches/controller_add_driver.yaml
assets/overlays/samba/patches/node_add_driver.yaml
cmd/generator/main.go
pkg/driver/common/generator/port_registry.go
pkg/driver/samba/samba.go
pkg/generator/asset_generator.go
pkg/generator/types.go

The patch ensures that all assets in `overlays/samba/generated/standalone` are generated by `generator`. Resulting assets survive simple dynamic-provisioning test with `test/e2e/samba/samba-server.yaml`

STOR-1726: auto-generate assets for CIFS/Samba driver

---

assets/overlays/azure-file/base/csidriver.yaml
assets/overlays/azure-file/generated/hypershift/csidriver.yaml
assets/overlays/azure-file/generated/standalone/csidriver.yaml

Without token audience static PVs fail to mount in workload identity clusters. This has been solved in AKS by adding token audience to CSIDriver:
https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1763
This API went GA in k/k 1.22:
https://github.com/kubernetes/kubernetes/pull/103001
1) Create a workload identity cluster with Flexy
2) Create a file share in Azure manually
3) Create static PV referencing the created file share
```
apiVersion: v1
kind: PersistentVolume
metadata:
annotations:
pv.kubernetes.io/provisioned-by: file.csi.azure.com
name: pv-azurefile
spec:
capacity:
storage: 10Gi
accessModes:
- ReadWriteMany
persistentVolumeReclaimPolicy: Retain
storageClassName: azurefile-csi
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=0
- gid=0
- mfsymlinks
- cache=strict
- …
```

OCPBUGS-32785: add token audience for Azure File

---

assets/overlays/aws-ebs/generated/hypershift/node.yaml
assets/overlays/aws-ebs/generated/standalone/node.yaml
pkg/driver/aws-ebs/aws_ebs.go

Port 10304 collides with aws-efs driver from 4.15. Let's use unused port 10309.

OCPBUGS-33776: Adjust port for registrar sidecar in aws-ebs csi driver container

---

test/e2e/samba/samba-server.yaml

- As the **[discussion](https://redhat-internal.slack.com/archives/GK0DA0JR5/p1715845060021839)**  we descide to use  these mountOptions as a suggested configuration in our [official doc](https://github.com/openshift/openshift-docs/pull/75920/files#diff-9feef84bc4321a98266556e517c2970f8444dab6f0fffad1a728c905502ed8f7R70-R75). Update the CI configuration consistent with official doc

NO-JIRA: keep smb test storageclass consistent with official doc

---

.ci-operator.yaml
Dockerfile.aws-ebs
Dockerfile.aws-efs
Dockerfile.azure-disk
Dockerfile.azure-file
Dockerfile.create_efs
Dockerfile.samba

Use go 1.22 in all images + .ci-operator.yaml

OCPBUGS-34451: Bump go version to be consistent with ART

---

pkg/driver/aws-efs/aws_efs.go
pkg/driver/aws-efs/aws_efs_test.go

This is the second attempt to set FIPS_ENABLED env var in aws-efs-csi-driver. [The first attempt](https://github.com/openshift/csi-operator/pull/245) depended on [library-go change](https://github.com/openshift/library-go/pull/1766) which was not nice because it could affect other users of library-go.
This PR is self-sufficient, it doesn't require any change in libarary-go.

OCPBUGS-37274: Add FIPS_ENABLED to env vars for aws-efs-csi-driver (2)

---

doc/aws-efs/README.md
pkg/driver/aws-efs/aws_efs.go
pkg/driver/aws-efs/aws_efs_test.go
pkg/generated-assets/generated_assets.go
pkg/operator/config/config.go
pkg/operator/starter.go

PR https://github.com/openshift/csi-operator/pull/237 for migrating EFS operator to csi-operator repo was missing credentials request hook - as a result EFS operator was not working in STS clusters due to missing secret:
```
MountVolume.SetUp failed for volume "aws-credentials" : secret "aws-efs-cloud-credentials" not found
```
Patch was tested to verify EFS dynamic provisioning on STS cluster and correct handling of role ARN provided via Operator Hub:
1) check provided ARN
```
$ oc -n openshift-cluster-csi-drivers get subscription/aws-efs-csi-driver-operator -o json | jq '.spec.config.env'
[
{
"name": "ROLEARN",
"value": "arn:aws:iam::269733383066:role/rbednar-aws-efs-openshift-cluster-csi-drivers-aws-efs-cloud-cred"
}
]
```
2) validate ARN propagated to cred. request by the hook
```
$ …
```

STOR-1856: add STS hook for EFS credentials request controller

---

assets/overlays/aws-ebs/generated/hypershift/controller.yaml
assets/overlays/aws-ebs/generated/standalone/controller.yaml
assets/overlays/aws-ebs/patches/controller_add_driver.yaml
go.mod
go.sum
pkg/driver/aws-ebs/aws_ebs_test.go
pkg/driver/common/operator/replacer.go
pkg/driver/common/operator/test_manifests/aws_ebs_controller_hypershift.yaml
vendor/github.com/openshift/library-go/pkg/operator/csi/csidrivercontrollerservicecontroller/helpers.go
vendor/modules.txt

The init container makes sure that `/var/run/secrets/aws/credentials` file exists and contains the AWS credentials. This is useful when CCO is in manual mode and doesn't create the `ebs-cloud-credentials` secret with the "credentials" key (this is supposed to be created manually). This key is projected as a file in the csi-driver container.
To be merged after https://github.com/openshift/cluster-storage-operator/pull/494 and https://github.com/openshift/library-go/pull/1769.
CC @openshift/storage

OCPBUGS-37488: add init container in EBS CSI controller pod

---

assets/overlays/azure-file/base/volumesnapshotclass.yaml
assets/overlays/azure-file/generated/hypershift/controller.yaml
assets/overlays/azure-file/generated/hypershift/main_snapshotter_binding.yaml
assets/overlays/azure-file/generated/hypershift/manifests.yaml
assets/overlays/azure-file/generated/hypershift/service.yaml
assets/overlays/azure-file/generated/hypershift/volumesnapshot_reader_provisioner_binding.yaml
assets/overlays/azure-file/generated/hypershift/volumesnapshotclass.yaml
assets/overlays/azure-file/generated/standalone/controller.yaml
assets/overlays/azure-file/generated/standalone/main_snapshotter_binding.yaml
assets/overlays/azure-file/generated/standalone/manifests.yaml
assets/overlays/azure-file/generated/standalone/service.yaml
assets/overlays/azure-file/generated/standalone/servicemonitor.yaml
assets/overlays/azure-file/generated/standalone/volumesnapshot_reader_provisioner_binding.yaml
assets/overlays/azure-file/generated/standalone/volumesnapshotclass.yaml
pkg/driver/azure-file/azure_file.go
test/e2e/azure-file/manifest.yaml

Driver logs with successful PVC and snapshot creation:
```
I0802 11:27:44.523693       1 utils.go:101] GRPC call: /csi.v1.Controller/CreateVolume
I0802 11:27:44.523715       1 utils.go:102] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-ce4d6eca-df1c-41dd-bb13-a484c0524ec6","parameters":{"csi.storage.k8s.io/pv/name":"pvc-ce4d6eca-df1c-41dd-bb13-a484c0524ec6","csi.storage.k8s.io/pvc/name":"pvc-1","csi.storage.k8s.io/pvc/namespace":"default","skuName":"Standard_LRS"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4","mount_flags":["mfsymlinks","cache=strict","nosharesock","actimeo=30"]}},"access_mode":{"mode":7}}]}
I0802 11:27:45.199848       1 controllerserver.go:561] begin to create file share(pvc-ce4d6eca-df1c-41dd-bb13-a484c0524ec6) on …
```

STOR-2002: add Azure File snapshot support

---

test/e2e/aws-ebs/ocp-manifest.yaml
test/e2e/azure-disk/ocp-manifest.yaml

The LUN stress test finished:
* In 20 minutes on AWS few times
* In 40 minutes on Azure.
Adding 20 minutes as a buffer.

STOR-1819: Add manifest with OCP specific test config

---

Dockerfile.create_efs

We need the AWS EFS OCP specific manifest available in CI. All other EFS tests manifests are generated by create-efs-volume image, so put this manifest there too.

STOR-1819: Distribute OCP specific test manifest with create-efs-volume

---

config/aws-efs/manifests/stable/image-references

change reference `ose-tools` to `ose-tools-rhel9`
related to https://github.com/openshift-eng/ocp-build-data/pull/5283

OCPBUGS-38578: Update aws-efs-csi-driver-operator image-references name

---

test/e2e/azure-disk/ocp-manifest.yaml

See OCPBUGS-41265, Azure reboots a node that is under heavy attach/detach load. Reduce the load dramatically until Azure provides a fix.

OCPBUGS-41265: Disable LUN stress test for azure-disk

---

README.md
doc/migrating-operators.md

This is far more discoverable and it allows us to iterate of the procedure faster. The enhancement will be updated to reference this new doc.

NO-JIRA: Move doc on migrating CSI Driver in-tree

---

Makefile
README.md

Update the README to list all currently supported operators.

NO-JIRA: List all supported operators in README

---

pkg/generator/types.go

To allow us to modify aspects of the default asset beyond 'args' without having to define a wholly new asset. We also add docs while we're here, mainly to emphasise that this shouldn't actually be used unless necessary.

NO-JIRA: Add SidecarConfig.WithPatches

---

assets/overlays/azure-file/base/storageclass.yaml
assets/overlays/azure-file/generated/hypershift/storageclass.yaml
assets/overlays/azure-file/generated/standalone/storageclass.yaml

This should address two issues:
- prevent matching storage accounts that have private endpoints enabled - this is the original issue in bug report
- prevent matching storage accounts that are not created by our operator - this is a side effect of using the tags, but we intended to address it anyway
The used key/value pair for the tag is unlikely to ever match any other storage account, although still possible if it is tagged the same. Another alternative considered was to hardcode storage account name (`storageAccount` param), but that requires having the storage account created in advance which is non-trivial and would add code to the operator that might not be necessary.

OCPBUGS-38922: add tag matching to Azure File storage class

---

pkg/driver/aws-efs/aws_efs.go

- We introduce the [standard approach](https://github.com/openshift/csi-operator/pull/215) when moving other OLM operators to csi-operator just by setting Removable: true in the OperatorConfig.
- The aws efs csi driver is an OLM based operator which should be removable when we delete the clustercsidriver the static resources should be removed directly.
**Test on local build aws efs csi driver operator paased with the fix patch**
```console
wangpenghao@pewang-mac  ~  oc get po
NAME                                             READY   STATUS    RESTARTS     AGE
aws-ebs-csi-driver-controller-64bbcdc4c7-qw28z   11/11   Running   0            9h
aws-ebs-csi-driver-controller-64bbcdc4c7-zv2mt   11/11   Running   4 (9h ago)   9h
aws-ebs-csi-driver-node-657tx                    3/3     Running …
```

OCPBUGS-42939: Correct aws efs csi driver config as removable

---

pkg/driver/openstack-cinder/openstack_cinder.go
pkg/operator/config/config.go

This is responsible for ensuring the daemonset is updated (and therefore new pods are rolled out) whenever credentials are changed. While we were doing this for the deployment (which manages controller pods), we had missed it for the deployment (which managed node pods). Correct that oversight.

OCPBUGS-43653: Add missing credentials secret hook

---

pkg/driver/openstack-cinder/openstack_cinder.go

This is responsible for transforming the `config.openshift.io/inject-proxy: csi-driver` annotation in the asset into `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` configuration. This is not currently done by default so we need to add it. Do that now.

OCPBUGS-43562: Add missing proxy hook for `openstack-cinder` driver

---

assets/overlays/azure-disk/generated/hypershift/controller.yaml
assets/overlays/azure-disk/patches/controller_add_hypershift_controller.yaml
assets/overlays/azure-file/generated/hypershift/controller.yaml
assets/overlays/azure-file/patches/controller_add_hypershift_controller.yaml

Set separate secrets for file and disk authentication config for Azure. Previously, these two components were reusing the same configuration as cloud provider.

OCPBUGS-42325: Set separate secrets for file and disk config on HyperShift

---

go.mod
pkg/driver/azure-disk/azure_disk.go
pkg/driver/azure-file/azure_file.go

Set the azure-disk and azure-file Secrets Store CSI volumes and volume mounts when the following environment variables are passed to the csi-operator pod - ARO_HCP_SECRET_PROVIDER_CLASS_FOR_FILE, ARO_HCP_SECRET_PROVIDER_CLASS_FOR_DISK.

HOSTEDCP-2032: Set azure disk & file Secrets Store CSI Volume

---

assets/overlays/openstack-cinder/OWNERS
cmd/openstack-cinder-csi-driver-operator/OWNERS
pkg/driver/openstack-cinder/OWNERS
pkg/openstack-cinder/OWNERS

This will be helpful as we work on Hypershift integration (though I still expect we'll want/need Storage guidance and reviews).
Note that this still won't let us merge changes to `openshift/release` since the `OWNERS` for that are generated from the root `OWNERS` file. I'm okay with just adding us to the root `OWNERS` file here, on the assumption that we'll only modify Cinder/Manila changes, but I will wait feedback first.

NO-JIRA: Add OWNERS files for OpenStack-specific components/assets

---

OWNERS
OWNERS_ALIASES

To allow us to review/approve OpenStack-related changes to `openshift/release`, since the `OWNERS` files there are auto-generated from this one.
This was previously suggested on https://github.com/openshift/csi-operator/pull/299.

NO-JIRA: Add openstack-approvers to root OWNERS

---

assets/overlays/openstack-manila/generated/hypershift/cabundle_cm.yaml
assets/overlays/openstack-manila/generated/hypershift/controller.yaml
assets/overlays/openstack-manila/generated/hypershift/controller_pdb.yaml
assets/overlays/openstack-manila/generated/hypershift/controller_sa.yaml
assets/overlays/openstack-manila/generated/hypershift/csidriver.yaml
assets/overlays/openstack-manila/generated/hypershift/lease_leader_election_binding.yaml
assets/overlays/openstack-manila/generated/hypershift/lease_leader_election_role.yaml
assets/overlays/openstack-manila/generated/hypershift/main_provisioner_binding.yaml
assets/overlays/openstack-manila/generated/hypershift/main_resizer_binding.yaml
assets/overlays/openstack-manila/generated/hypershift/main_snapshotter_binding.yaml
assets/overlays/openstack-manila/generated/hypershift/manifests.yaml
assets/overlays/openstack-manila/generated/hypershift/node.yaml
assets/overlays/openstack-manila/generated/hypershift/node_nfs.yaml
assets/overlays/openstack-manila/generated/hypershift/node_privileged_binding.yaml
assets/overlays/openstack-manila/generated/hypershift/node_sa.yaml
assets/overlays/openstack-manila/generated/hypershift/privileged_role.yaml
assets/overlays/openstack-manila/generated/hypershift/service.yaml
assets/overlays/openstack-manila/generated/hypershift/storageclass_reader_resizer_binding.yaml
assets/overlays/openstack-manila/generated/hypershift/volumesnapshot_reader_provisioner_binding.yaml
assets/overlays/openstack-manila/generated/hypershift/volumesnapshotclass.yaml
assets/overlays/openstack-manila/patches/controller_add_hypershift_volumes.yaml
assets/overlays/openstack-manila/patches/controller_rename_config_map.yaml
pkg/driver/openstack-manila/openstack_manila.go
pkg/openstack-manila/secret/secretsync.go

This PR includes the Manila assets to Hypershift. It also uses a config-map that is generated by Hypershift and updates how the certificate is populated in the secret synced.

OSASINFRA-3638: Add support for Hypershift to Manila CSI

---

pkg/driver/openstack-manila/openstack_manila.go
pkg/operator/starter_controller.go
pkg/operator/starter_controller_test.go

This commit handles the error returned by syncing operations
on the starter controller and only marks the operator as disabled
if no manila share types is available.

OCPBUGS-44340: Fix error handling for starter controller

---

.snyk

https://github.com/openshift/csi-operator/pull/287 introduced some new noise in the ci/prow/security job:
```
✗ [Medium] Path Traversal
ID: d4eae1cf-1400-4b06-a906-bc189fed8faf 
Path: cmd/generator/main.go, line 39 
Info: Unsanitized input from a CLI argument flows into os.RemoveAll, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to delete arbitrary files.
```
cmd/generator/main.go is just a tool to generate static assets, not something an attacker could leverage to delete a file they couldn't otherwise delete.

NO-JIRA: ignore cmd/generator/main.go in .snyk

---

README.md
assets/overlays/openstack-manila/generated/hypershift/controller.yaml
assets/overlays/openstack-manila/generated/standalone/controller.yaml
pkg/driver/openstack-manila/openstack_manila.go
test/e2e/openstack-manila/manifest.yaml

Volume expansion is a mandatory feature supported
within back end drivers in OpenStack Manila. To
enable this with the Manila CSI driver, the operator needs to specify the external resizer sidecar along with its appropriate RBAC, and set "allowVolumeExpansion" to True. Volume expansion for NAS shared file systems is a controller-only operation; there's no node plugin operations necessary unlike block storage.

OSASINFRA-3626: Resize support with the OpenStack Manila CSI Driver

---

assets/overlays/openstack-manila/generated/hypershift/controller.yaml
assets/overlays/openstack-manila/generated/hypershift/controller_pdb.yaml
assets/overlays/openstack-manila/generated/hypershift/service.yaml
assets/overlays/openstack-manila/generated/standalone/controller.yaml
assets/overlays/openstack-manila/generated/standalone/controller_pdb.yaml
assets/overlays/openstack-manila/generated/standalone/service.yaml
assets/overlays/openstack-manila/patches/controller_add_driver.yaml
assets/overlays/openstack-manila/patches/modify_anti_affinity_selector.yaml
assets/overlays/openstack-manila/patches/modify_match_labels.yaml
assets/overlays/openstack-manila/patches/modify_service_selector.yaml
pkg/driver/openstack-manila/openstack_manila.go

This commit updates the selectors used in the controller Deployment,
PodDisruptionBudget and the controller metrics Service to actually use
the labels that are enforced in the controller.

OCPBUGS-45267: openstack-manila: modify assets selectors

---

assets/overlays/aws-efs/generated/standalone/controller.yaml
assets/overlays/aws-efs/generated/standalone/service.yaml
assets/overlays/aws-efs/generated/standalone/servicemonitor.yaml
pkg/driver/aws-efs/aws_efs.go

EFS driver does not support metrics, this was added by mistake when migrating code to this repo.
Before patch:
```
$ oc -n openshift-cluster-csi-drivers logs pod/aws-efs-csi-driver-controller-664d67f4d8-44lqg -c kube-rbac-proxy-8211
W1121 14:42:17.000703       1 deprecated.go:66]
==== Removed Flag Warning ======================
logtostderr is removed in the k8s upstream and has no effect any more.
===============================================
I1121 14:42:17.001127       1 kube-rbac-proxy.go:233] Valid token audiences:
I1121 14:42:17.001183       1 kube-rbac-proxy.go:347] Reading certificate files
I1121 14:42:17.001379       1 kube-rbac-proxy.go:395] Starting TCP socket on 0.0.0.0:9211
I1121 14:42:17.001613       1 kube-rbac-proxy.go:402] Listening securely on 0.0.0.0:9211
I1121 …
```

OCPBUGS-44723: remove EFS driver metrics

---

assets/base/rbac/volumeattributesclass_reader_provisioner_binding.yaml
assets/base/rbac/volumeattributesclass_reader_resizer_binding.yaml
assets/overlays/aws-ebs/generated/hypershift/manifests.yaml
assets/overlays/aws-ebs/generated/hypershift/volumeattributesclass_reader_provisioner_binding.yaml
assets/overlays/aws-ebs/generated/hypershift/volumeattributesclass_reader_resizer_binding.yaml
assets/overlays/aws-ebs/generated/standalone/manifests.yaml
assets/overlays/aws-ebs/generated/standalone/volumeattributesclass_reader_provisioner_binding.yaml
assets/overlays/aws-ebs/generated/standalone/volumeattributesclass_reader_resizer_binding.yaml
pkg/driver/aws-ebs/aws_ebs.go

Add RBAC ClusterRoleBinding for resizer + provisioner

STOR-2078: Enable VolumeAttributesClass on AWS EBS for resizer + provisioner

---

assets/overlays/openstack-manila/generated/hypershift/controller_pdb.yaml
assets/overlays/openstack-manila/generated/standalone/controller_pdb.yaml
assets/overlays/openstack-manila/patches/modify_pdb.yaml
pkg/driver/openstack-manila/openstack_manila.go

In previous releases the PodDisruptionBudget is named openstack-manila-csi-controllerplugin-pdb instead of manila-csi-driver-controller-pdb, which is the name currently generated by csi-operator. This prevents upgrades from being successful. To fix the issue the asset is renamed with the same name as used in previous releases.

OCPBUGS-48507: openstack-manila: update PodDisruptionBudget name

---

assets/overlays/aws-ebs/generated/hypershift/node.yaml
assets/overlays/aws-ebs/generated/standalone/node.yaml
assets/overlays/aws-ebs/patches/node_add_driver.yaml
assets/overlays/aws-efs/generated/standalone/node.yaml
assets/overlays/aws-efs/patches/node_add_driver.yaml

There is no proxy hook configured for either driver making this a no-op. Remove it.

NO-JIRA: Remove `inject-proxy` annotations for aws-ebs, aws-efs node daemonsets

---

assets/overlays/samba/base/csi-driver-cluster-role-binding.yaml
assets/overlays/samba/base/csi-driver-cluster-role.yaml
assets/overlays/samba/base/csidriver.yaml
assets/overlays/samba/generated/standalone/controller.yaml
assets/overlays/samba/generated/standalone/csi-driver-cluster-role-binding.yaml
assets/overlays/samba/generated/standalone/csi-driver-cluster-role.yaml
assets/overlays/samba/generated/standalone/csidriver.yaml
assets/overlays/samba/generated/standalone/main_resizer_binding.yaml
assets/overlays/samba/generated/standalone/manifests.yaml
assets/overlays/samba/generated/standalone/service.yaml
assets/overlays/samba/generated/standalone/servicemonitor.yaml
assets/overlays/samba/generated/standalone/storageclass_reader_resizer_binding.yaml
config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml
pkg/driver/samba/samba.go
test/e2e/samba/manifest.yaml
test/e2e/samba/samba-server.yaml

- Enable csi resize support for smb csi driver (upstream ref: https://github.com/kubernetes-csi/csi-driver-smb/pull/881)
- Enable csi inline volume support for smb csi driver (upstream ref: https://github.com/kubernetes-csi/csi-driver-smb/pull/905)

STOR-2263: Enable csi resize and inline volume support for smb csi driver

---

test/e2e/samba/manifest.yaml

- Upstream fix -> https://github.com/kubernetes-csi/csi-driver-smb/pull/931
- Correct the smb csi driver test manifest(actually the driver does not support `nodeExpansion `), follow up of https://github.com/openshift/csi-operator/pull/358#discussion_r1961987181 .

STOR-2263: correct smb csi driver test manifest

---

assets/overlays/azure-disk/generated/hypershift/node.yaml
assets/overlays/azure-disk/generated/standalone/controller.yaml
assets/overlays/azure-disk/generated/standalone/node.yaml
assets/overlays/azure-disk/patches/controller_add_standalone_injector.yaml
assets/overlays/azure-disk/patches/node_add_driver.yaml
assets/overlays/azure-file/generated/hypershift/node.yaml
assets/overlays/azure-file/generated/standalone/controller.yaml
assets/overlays/azure-file/generated/standalone/node.yaml
assets/overlays/azure-file/patches/controller_add_standalone_injector.yaml
assets/overlays/azure-file/patches/node_add_driver.yaml

Based on discussion https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/380#issuecomment-2668448871  pr https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/385 will keep both the secret and environment variables methods, then this pr can be merged, then remove environment variables in pr https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/380
Built image [build 4.18,openshift/cluster-cloud-controller-manager-operator#385](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/release-openshift-origin-installer-launch-aws-modern/1894239232529010688) and installed cluster on azure and ash, cluster install succeed.
Built image [build 4.18,openshift/cluster-cloud-controller-manager-operator#385, …

OCPBUGS-41827: update injector to use a secret rather than an environment variable

---

assets/overlays/azure-disk/generated/hypershift/node.yaml
assets/overlays/azure-disk/generated/standalone/node.yaml
assets/overlays/azure-disk/patches/node_add_driver.yaml

- Disable the remove-not-ready-taint feature, as it is not implemented in ocp, avoid the unnecessary remove taint actions and logs. (Try to make it opt-in on upstream but unfortunately the maintainer is not happy with it, so we could go head disable it from our operator side. https://redhat-internal.slack.com/archives/GK0DA0JR5/p1743062502904419?thread_ts=1742823634.580139&cid=GK0DA0JR5)

OCPBUGS-54180: Disable remove-not-ready-taint for azure disk csi driver

---

assets/overlays/openstack-manila/generated/hypershift/controller.yaml
assets/overlays/openstack-manila/generated/hypershift/node.yaml
assets/overlays/openstack-manila/generated/standalone/controller.yaml
assets/overlays/openstack-manila/generated/standalone/node.yaml
assets/overlays/openstack-manila/patches/controller_add_driver.yaml
assets/overlays/openstack-manila/patches/node_add_driver.yaml

The Manila CSI driver, like Cinder, uses a single binary for both the controller and node (worker) services. This can result in services running on unintended hosts. A similar issue was addressed in Cinder in version 4.18, and we should now apply the same fix to Manila.

OCPBUGS-54447: Enable required driver services

---

config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
config/samba/manifests/stable/smb-csi-driver-operator.clusterserviceversion.yaml

Enable readOnlyFileSystem in the operator for security concerns.
Recommended for all containers running in kubernetes.

STOR-2126: Enable readOnlyFileSystem

---

pkg/driver/azure-disk/azure_disk.go

- We made a mistake when migrate the azure disk driver operator from `azure-disk-csi-driver-operator` to `csi-operator`, the  `injectEnvAndMounts` which used for ASH the `endpoints` Subpath expected read the `endpoints` value from the cloud configmap key `endpoints` while we use the incorrect volume name for injecting.
ref -> https://github.com/openshift/azure-disk-csi-driver-operator/blob/release-4.15/pkg/azurestackhub/azure_stack_hub.go#L48-L76
```console
...
2025-03-27T21:07:32.105160383Z W0327 21:07:32.105102       1 azure_disk_utils.go:236] InitializeCloudFromConfig failed with error: read /etc/azure/azurestackcloud.json: is a directory 
...
```

OCPBUGS-54382: Correct ASH driver inject env config

---

assets/overlays/openstack-cinder/generated/hypershift/node.yaml
assets/overlays/openstack-cinder/generated/standalone/node.yaml
assets/overlays/openstack-cinder/patches/node_add_driver.yaml

This is a follow-up to https://github.com/openshift/csi-operator/pull/345. Failure to do so results in the node driver reporting topology information which the provisioner respects, preventing us attaching the created volume.

OCPBUGS-56128: openstack-cinder: Set --with-topology flag for node driver also

---

assets/overlays/openstack-cinder/generated/hypershift/controller.yaml
assets/overlays/openstack-cinder/generated/standalone/controller.yaml
assets/overlays/openstack-cinder/patches/controller_add_driver.yaml
assets/overlays/openstack-manila/generated/hypershift/controller.yaml
assets/overlays/openstack-manila/generated/hypershift/service.yaml
assets/overlays/openstack-manila/generated/standalone/controller.yaml
assets/overlays/openstack-manila/generated/standalone/service.yaml
assets/overlays/openstack-manila/generated/standalone/servicemonitor.yaml
assets/overlays/openstack-manila/patches/controller_add_driver.yaml
pkg/driver/openstack-manila/openstack_manila.go

Modify the Cinder operator so that it starts reporting controller driver metrics correctly.
Modify the Manila operator so that we stop creating a controller driver metrics proxy container, since the controller driver does not currently support reporting metrics.

OCPBUGS-54975: Fix Cinder, Manila driver metrics

---

config/aws-efs/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml

https://issues.redhat.com//browse/STOR-2331
This PR subscribes AWS-EFS CSI driver operator pods to NPs from https://github.com/openshift/cluster-storage-operator/pull/579

STOR-2331: Add labels to subscribe AWS-EFS CSI driver operator to NPs

---

go.mod
go.sum
pkg/clients/builder.go
vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/networking.go
vendor/github.com/openshift/library-go/pkg/operator/v1helpers/informers.go
vendor/modules.txt

https://issues.redhat.com/browse/OCPBUGS-54385
Most of controllers do per-controller resync, so informer resync is redundant. The only exception is LogLevel controller, but it must be safe to call reconciliation loop when an update happens without resync.

OCPBUGS-54385: Avoid informer resync
